apiVersion: v1
kind: ConfigMap
metadata:
  name: ext-backend-configmap
data:
  mongo_host: mongodb-service
  mongo_port: 27017
  mongo_databaase: "project"
  nodemailer_host": "smtp.gmail.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: ext-backend-secret
type: Opaque
data:
  secret_session: cGFzc3dvcmQ=
  nodemailer_email: YWFyb25jb2MwMDEwQGdtYWlsLmNvbQ==
  nodemailer_password: Yml6dGltZTEyMw==
